/**
 * End-to-end claim test — simulates the user calling claimRewards on-chain.
 * The signature was already generated by the AWS /claim-signature endpoint.
 *
 * Usage:
 *   DEPLOYER_PRIVATE_KEY=0x... \
 *   VIGIA_CONTRACT_ADDRESS=0x... \
 *   CLAIM_AMOUNT=2000000000000000000 \
 *   CLAIM_NONCE=0 \
 *   CLAIM_SIGNATURE=0x9e12... \
 *   RECIPIENT=0x35b0... \
 *   npx hardhat run scripts/verify-claim.ts --network amoy
 */

import { ethers } from "hardhat";

const CLAIM_ABI = [
  "function claimRewards(uint256 amount, uint256 nonce, bytes calldata signature) external",
  "function balanceOf(address) view returns (uint256)",
  "function burnForDataCredits(uint256 amount) external",
  "function dataCredits(address) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
];

async function main() {
  const contractAddress = process.env.VIGIA_CONTRACT_ADDRESS!;
  const amount = process.env.CLAIM_AMOUNT!;
  const nonce = parseInt(process.env.CLAIM_NONCE || "0");
  const signature = process.env.CLAIM_SIGNATURE!;
  const recipient = process.env.RECIPIENT || "0x35b0Ec7B2172d1a1C8367C312246786632DE9427";

  if (!contractAddress || !amount || !signature) {
    console.error("Missing: VIGIA_CONTRACT_ADDRESS, CLAIM_AMOUNT, CLAIM_SIGNATURE");
    process.exit(1);
  }

  const [signer] = await ethers.getSigners();
  const contract = new ethers.Contract(contractAddress, CLAIM_ABI, signer);

  console.log("Contract:", contractAddress);
  console.log("Claimer (pays gas):", signer.address);
  console.log("Recipient:", recipient);

  // ── Step 1: Balance before ───────────────────────────────────────────────
  const before = await contract.balanceOf(recipient);
  const supply = await contract.totalSupply();
  console.log("\nBefore claim:");
  console.log("  Recipient VGA balance:", ethers.formatUnits(before, 18));
  console.log("  Total supply:", ethers.formatUnits(supply, 18));

  // ── Step 2: claimRewards (user pays gas, KMS pays nothing) ───────────────
  console.log("\nSubmitting claimRewards...");
  const claimTx = await contract.claimRewards(amount, nonce, signature);
  console.log("  txHash:", claimTx.hash);
  await claimTx.wait();
  console.log("  ✅ Confirmed");

  // ── Step 3: Balance after ────────────────────────────────────────────────
  const after = await contract.balanceOf(recipient);
  console.log("\nAfter claim:");
  console.log("  Recipient VGA balance:", ethers.formatUnits(after, 18));
  console.log("  Tokens received:", ethers.formatUnits(after - before, 18));

  // ── Step 4: Enterprise burnForDataCredits ────────────────────────────────
  console.log("\nTesting burnForDataCredits(1 VGA)...");
  // Signer needs 1 VGA — transfer some first if needed
  const signerBal = await contract.balanceOf(signer.address);
  if (signerBal >= ethers.parseUnits("1", 18)) {
    const burnTx = await contract.burnForDataCredits(ethers.parseUnits("1", 18));
    console.log("  txHash:", burnTx.hash);
    await burnTx.wait();
    const credits = await contract.dataCredits(signer.address);
    const supplyAfter = await contract.totalSupply();
    console.log("  ✅ dataCredits:", ethers.formatUnits(credits, 18));
    console.log("  Total supply after burn:", ethers.formatUnits(supplyAfter, 18));
  } else {
    console.log("  [SKIP] Signer has no VGA to burn — transfer some first");
  }

  console.log("\n✅ Phase 3 complete — full BME lifecycle verified on-chain!");
  console.log(`PolygonScan: https://amoy.polygonscan.com/tx/${claimTx.hash}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
